Repository mumax/plus, pull requests merged in 2025-09, with the labels that each got.

#98 Add google analytics
  docs/_static/google-analytics.js
  docs/conf.py
Labels: documentation, enhancement

#96 Show rework
  docs/examples/voronoi.rst
  docs/images/DW_SAW.png
  docs/images/DW_SAW2.png
  docs/images/DW_mag.png
  docs/images/antivortex_mag.png
  docs/images/blochskyrm_mag.png
  docs/images/function_mag.png
  docs/images/neelskyrm_mag.png
  docs/images/rainbow_mag.png
  docs/images/random_mag.png
  docs/images/regions_1.png
  docs/images/regions_2.png
  docs/images/stdp4_1.png
  docs/images/stdp4_2.png
  docs/images/stdp4_3.png
  docs/images/uniform_mag.png
  docs/images/voronoi.png
  docs/images/voronoi_final.png
  docs/images/voronoi_init.png
  docs/images/voronoi_regions.png
  docs/images/vortex_mag.png
  docs/tutorial/magnetization.rst
  docs/tutorial/regions.rst
  docs/tutorial/stdp4.rst
  examples/DW_rigid_strain_SAW.py
  examples/MRAM_bit_switch.py
  examples/electricpotential.py
  examples/magnetization_configurations.ipynb
  examples/mfm.py
  examples/multilayer.py
  examples/periodic_bc.py
  examples/plot_field.ipynb
  examples/regions.ipynb
  examples/skyrmion_excitation.py
  examples/skyrmionracetrack.py
  examples/standardproblem3.py
  examples/standardproblem4.ipynb
  examples/temperature.py
  examples/voronoi.py
  mumaxplus/fieldquantity.py
  mumaxplus/util/__init__.py
  mumaxplus/util/show.py
  src/core/fieldops.cu
Labels: enhancement

#99 Fix bug of minor bug fix in homogeneous AFM exchange calculation
  src/physics/afmexchange.cu
Labels: bug
